// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfrxsnvjzcxpafbfffgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcnhzbnZqemN4cGFmYmZmZmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NDkxNzYsImV4cCI6MjA1NTUyNTE3Nn0.N0pAxBkGVHQs69gGtx2oT5TbNECuImUGqssKAnv1M4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);